import React from 'react';
import { motion } from 'framer-motion';
import { FileText } from 'lucide-react';

const TermsOfService: React.FC = () => {
  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
  };

  return (
    <motion.div
      className="min-h-screen bg-[#0b0f1a] py-12"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.5 }}
    >
      <div className="container mx-auto px-4 max-w-4xl">
        {/* Header */}
        <motion.div
          className="mb-12"
          variants={itemVariants}
          initial="hidden"
          animate="visible"
        >
          <div className="flex items-center gap-3 mb-4">
            <FileText className="h-8 w-8 text-blue-400" />
            <h1 className="text-4xl font-bold text-white">Terms of Service</h1>
          </div>
          <p className="text-gray-400">Last updated: January 22, 2026</p>
        </motion.div>

        {/* Content */}
        <motion.div
          className="space-y-8"
          variants={itemVariants}
          initial="hidden"
          animate="visible"
          transition={{ staggerChildren: 0.1, delayChildren: 0.2 }}
        >
          <section>
            <h2 className="text-2xl font-bold text-white mb-4">1. Agreement to Terms</h2>
            <p className="text-gray-300 leading-relaxed">
              By accessing and using inceptIQ, you accept and agree to be bound by the terms and provision of this
              agreement. If you do not agree to abide by the above, please do not use this service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">2. Use License</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              Permission is granted to temporarily download one copy of the materials (information or software) on
              inceptIQ for personal, non-commercial transitory viewing only. This is the grant of a license, not a
              transfer of title, and under this license you may not:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2">
              <li>Modifying or copying the materials</li>
              <li>Using the materials for any commercial purpose or for any public display</li>
              <li>Attempting to decompile or reverse engineer any software contained on inceptIQ</li>
              <li>Removing any copyright or other proprietary notations from the materials</li>
              <li>Transferring the materials to another person or "mirroring" the materials on any other server</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">3. Disclaimer</h2>
            <p className="text-gray-300 leading-relaxed">
              The materials on inceptIQ are provided on an 'as is' basis. inceptIQ makes no warranties, expressed or
              implied, and hereby disclaims and negates all other warranties including, without limitation, implied
              warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of
              intellectual property or other violation of rights.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">4. Limitations</h2>
            <p className="text-gray-300 leading-relaxed">
              In no event shall inceptIQ or its suppliers be liable for any damages (including, without limitation,
              damages for loss of data or profit, or due to business interruption) arising out of the use or
              inability to use the materials on inceptIQ.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">5. Analysis Disclaimer</h2>
            <p className="text-gray-300 leading-relaxed">
              The analysis results provided by inceptIQ are generated by artificial intelligence and should not be
              considered as professional investment, business, or legal advice. We do not guarantee the accuracy or
              completeness of the analysis. Always consult with qualified professionals before making business
              decisions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">6. Accuracy of Materials</h2>
            <p className="text-gray-300 leading-relaxed">
              The materials appearing on inceptIQ could include technical, typographical, or photographic errors.
              inceptIQ does not warrant that any of the materials on inceptIQ are accurate, complete, or current.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">7. Materials and Content</h2>
            <p className="text-gray-300 leading-relaxed">
              inceptIQ has not reviewed all of the sites linked to its website and is not responsible for the
              contents of any such linked site. The inclusion of any link does not imply endorsement by inceptIQ of
              the site. Use of any such linked website is at the user's own risk.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">8. Modifications</h2>
            <p className="text-gray-300 leading-relaxed">
              inceptIQ may revise these terms of service for our website at any time without notice. By using this
              website, you are agreeing to be bound by the then current version of these terms of service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">9. Governing Law</h2>
            <p className="text-gray-300 leading-relaxed">
              These terms and conditions are governed by and construed in accordance with the laws of the jurisdiction
              in which inceptIQ operates, and you irrevocably submit to the exclusive jurisdiction of the courts
              located in that location.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">10. User Responsibilities</h2>
            <p className="text-gray-300 leading-relaxed mb-4">
              As a user of inceptIQ, you agree to:
            </p>
            <ul className="list-disc list-inside text-gray-300 space-y-2">
              <li>Provide accurate and complete information during registration</li>
              <li>Maintain the confidentiality of your account credentials</li>
              <li>Not use the service for any illegal or unauthorized purpose</li>
              <li>Not transmit viruses or malicious code</li>
              <li>Not attempt to gain unauthorized access to our systems</li>
              <li>Respect intellectual property rights</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-white mb-4">11. Contact Information</h2>
            <p className="text-gray-300 leading-relaxed">
              If you have any questions about these Terms of Service, please contact us at:
            </p>
            <div className="mt-4 p-4 bg-gray-800/50 border border-gray-700 rounded-lg">
              <p className="text-white font-semibold">Email: support@inceptiq.com</p>
              <p className="text-gray-400 text-sm mt-2">We'll respond within 24 hours</p>
            </div>
          </section>
        </motion.div>
      </div>
    </motion.div>
  );
};

export default TermsOfService;

